apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: pgdata, namespace: agent-stack }
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 1Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: postgres, namespace: agent-stack }
spec:
  replicas: 1
  selector: { matchLabels: { app: postgres } }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - { name: POSTGRES_PASSWORD, value: example }
        - { name: POSTGRES_DB, value: app }
        ports: [ { containerPort: 5432 } ]
        volumeMounts: [ { name: data, mountPath: /var/lib/postgresql/data } ]
      volumes:
      - name: data
        persistentVolumeClaim: { claimName: pgdata }
---
apiVersion: v1
kind: Service
metadata: { name: postgres, namespace: agent-stack }
spec:
  selector: { app: postgres }
  ports: [ { port: 5432, targetPort: 5432 } ]
